FLIGHT PRICE PREDICTION PROJECT- WEB SCRAPING

In [47]:
#!pip install selenium

WEB SCRAPING FLIGHT PRICES FROM www.kayak.co.in

In [4]:
import time
import selenium
from selenium import webdriver
import pandas as pd
import numpy as np
import time
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
from selenium.common.exceptions import NoSuchElementException,StaleElementReferenceException,TimeoutException,ElementClickInterceptedException

In [2]:
#creating a function to scrape text from a list
def scrape_text(web_el):
    list1=[]
    for i in web_el:
        try:
            
            list1.append(i.text.replace("\n",","))
        except Exception as e:
            print("exception in scrape_text",e)
            list1.append("--")
    return list1

The origin and destination city names searched at the first sitting have been recorded in these two lists so that we can scrape similar flight details for different dates.

In [1045]:
origin_names=[]
destination_names=[]

In [1928]:
print("origin names :",origin_names)
print("destination_names",destination_names)

origin names : ['mumbai', 'delhi', 'delhi', 'delhi', 'delhi', 'delhi', 'delhi', 'delhi', 'delhi', 'cape town', 'chicago', 'miami', 'miami', 'miami', 'miami', 'mumbai', 'mumbai', 'mumbai', 'mumbai', 'patna', 'delhi', 'patna', 'banglore', 'kolkata', 'chennai', 'ahmedabad', 'pune', 'cape town', 'toronto', 'toronto', 'toronto', 'toronto', 'chicago', 'pune', 'ahmedabad']
destination_names ['delhi', 'patna', 'banglore', 'kolkata', 'chennai', 'ahmedabad', 'pune', 'cape town', 'toronto', 'toronto', 'toronto', 'toronto', 'chicago', 'boston', 'barcelona', 'pune', 'ahmedabad', 'chennai', 'banglore', 'banglore', 'mumbai', 'delhi', 'delhi', 'delhi', 'delhi', 'delhi', 'delhi', 'delhi', 'delhi', 'cape town', 'chicago', 'miami', 'miami', 'mumbai', 'mumbai']

In [3]:
df_search=pd.read_csv('Flight_price(searched)')
df_search

    Unnamed: 0 origin_names destination_names
0            0       mumbai             delhi
1            1        delhi             patna
2            2        delhi          banglore
3            3        delhi           kolkata
4            4        delhi           chennai
5            5        delhi         ahmedabad
6            6        delhi              pune
7            7        delhi         cape town
8            8        delhi           toronto
9            9    cape town           toronto
10          10      chicago           toronto
11          11        miami           toronto
12          12        miami           chicago
13          15       mumbai              pune
14          16       mumbai         ahmedabad
15          17       mumbai           chennai
16          18       mumbai          banglore
17          19        patna          banglore
18          20        delhi            mumbai
19          21        patna             delhi
20          22     banglore             delhi
21          23      kolkata             delhi
22          24      chennai             delhi
23          25    ahmedabad             delhi
24          26         pune             delhi
25          27    cape town             delhi
26          28      toronto             delhi
27          29      toronto         cape town
28          30      toronto           chicago
29          31      toronto             miami
30          32      chicago             miami
31          33         pune            mumbai
32          34    ahmedabad            mumbai
33          35      chennai            mumbai
34          36     banglore            mumbai
35          37     banglore             patna

In [4]:
df_search.drop('Unnamed: 0',axis=1,inplace=True)

In [5]:
#Loading the webdriver
driver=webdriver.Chrome(r"C:\python\chromedriver96\chromedriver")

PART-A(start)

In [1309]:
#browsing the website
url='https://www.kayak.co.in/'
driver.get(url)

In [578]:
#maximizing the browser-window size
driver.maximize_window()

In [1310]:
#Clearing "Originating" from column
clear_depart=driver.find_elements_by_xpath("//div[@class='vvTc-item-button']")
clear_depart[0].click()

The below code is used to keep sending keys(cities) origin and destination,to be searched.

In [1311]:
#count=-1
count=count+1
print(count)

35

In [1312]:
key2=df_search['destination_names'][count]
key1=df_search['origin_names'][count]

In [1313]:
#Sending the name of the place of departure
depart=driver.find_element_by_xpath("//input[@class='k_my-input']")
depart.send_keys(key1)

In [1314]:
#Pressing the enter button
depart.send_keys(Keys.ENTER)
#origin_names.append(key1)

In [1315]:
#Clearing "arriving" at column
clear_depart=driver.find_elements_by_xpath("//div[@class='vvTc-item-button']")
clear_depart[1].click()

In [1316]:
#Clicking the "Arrival at/destination" box
try:
    destination_=driver.find_elements_by_xpath("//div[@class='lNCO-inner']")
    destination_[1].click()
except ElementClickInterceptedException as p:
    print("exception raised",p)

exception raised Message: element click intercepted: Element <div class="lNCO-inner">...</div> is not clickable at point (744, 235). Other element would receive the click: <input type="text" class="k_my-input" tabindex="-1" aria-disabled="false" placeholder="To?" value="">
  (Session info: chrome=97.0.4692.99)

For the below code to execute,the browser page in which the tasks are being performed have to be opened and minimized once,else it will throw a NoSuchElementException.

In [1317]:
#Entering destination
destination=driver.find_element_by_xpath("//div[@class='k_my k_my-mod-theme-none k_my-mod-variant-bold k_my-mod-size-medium k_my-mod-font-size-base k_my-mod-spacing-none k_my-mod-text-overflow-ellipsis k_my-mod-state-default']//input")

In [1318]:
#Entering the destination name 
destination.send_keys(key2)

In [1319]:
#Pressing the enter key
destination.send_keys(Keys.ENTER)
#destination_names.append(key2)

In [147]:
#Changing flight settings from return to one-way(only to be used once)
#change_=driver.find_elements_by_xpath("//span[@class='svg wIIH-chevron-icon-wrapper']")
#change_[0].click()

PART-A(end)
PART_A needs to be executed every time we change the origin or the destination(or both).

PART-B(start)

In [22]:
#Changing dates
date_el=driver.find_element_by_xpath("//div[@class='cQtq-input']")
date_el.click()

In [20]:
#scrolling the date to january
date_arrow=driver.find_element_by_xpath("//div[@class='Fj7W-arrow']")
date_arrow.click()

In [24]:
#clicking_on the desired date(28th jan)
date=driver.find_element_by_xpath("//div[@aria-label='13 February, 2022']")
date.click()

PART-B(end)
The part-B has to be executed only once at the time of setting up the date for which the flights are to be searched.

In [1320]:
#Clicking search button 
search=driver.find_elements_by_xpath("//div[@class='Iqt3-button-content']")
search[2].click()

PART-C(start)

In [ ]:
#Changing flight settings from return to one-way
change_=driver.find_elements_by_xpath("//ul[@class='_iKm _id7 _2s _iOC _iFZ _iA6 _2x _2y _iFW _2p _2Q']//li")
change_[1].click()

In [421]:
#To be used only once after changing the flight filter from "return" to "One-way"
search_new=driver.find_element_by_xpath("//div[@class='Common-Widgets-Button-StyleJamButton ui-button size-m _id7 _ihr _ihs _h-Y _im4 _ii0 _ihp _ihq _inw _iir _iae _imQ _iv1 _is5 _iEH _iGL _i75 _iTr _iED _inn _is4 _jWp _i4n _jWq _iqH _ikc _jWo _iCU _iCV _iqF _ia1 _ijv _ibo _jeQ _iHQ _iP9 _jMo _iiN _iTB _jWt _jWu _jWs _jUM']")
search_new.click()

PART-C(end)
PART-C is basically there to change the flight settings from 'return' to 'one-way'.If the PART-B does not work,click the option manually.

In [1321]:
#Clicking the "cheapest" option 
option_cheapest=driver.find_elements_by_xpath("//div[@class='_iKN _iae _igf _ibA _ian _iai _i3E _ia- _igO']")
option_cheapest[0].click()

In [1328]:
#Clicking "show more results" tab(present in some routes,throws a NoSuchElementException if the tab isn't availabble )
try:
    show_more=driver.find_element_by_xpath("//div[@class='Common-Results-Paginator ButtonPaginator visible']")
    show_more.click()
except NoSuchElementException as e:
    print("Tab not visible",e)

Tab not visible Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class='Common-Results-Paginator ButtonPaginator visible']"}
  (Session info: chrome=97.0.4692.99)

PART-D(start)

In [49]:
#Function to extract website name
def get_website():
    website=driver.find_elements_by_xpath("//span[@class='name-only-text']")
    time.sleep(1)
    return website

In [50]:
#Function to extract airline names
def get_airline():
    airline=driver.find_elements_by_xpath("//span[@class='codeshares-airline-names']")
    time.sleep(1)
    return airline

In [440]:
#Fucntion to extract departure and arrival times
def get_times():
    times__=[]
    times=driver.find_elements_by_xpath("//span[@class='time-pair']")
    #time.sleep(1)
    #for i in times:
     #   if(i!=''):
      #      times__.append(i)
    return times

In [442]:
#Function to get airport names
def get_airports():
    airport__=[]
    airport=driver.find_elements_by_xpath("//div[@class='bottom-airport']")or("//div[@class='bottom-airport flag']")
    #time.sleep(1)
    #for i in airport:
     #   if(i!=''):
      #      airport__.append(i)
    return airport

In [443]:
#Function to extract Number and name of stops
def get_stops():
    stops__=[]
    stops=driver.find_elements_by_xpath("//div[@class='section stops']")
    #time.sleep(1)
    #for i in stops:
     #   if(i!=''):
      #      stops__.append(i)
    return stops

In [444]:
#Function to extract duration of journey
def get_duration():
    duration__=[]
    duration=driver.find_elements_by_xpath("//div[@class='section duration allow-multi-modal-icons']")
    #time.sleep(1)
    #for i in duration:
      #if(i!=''):
       #     duration__.append(i)
    return duration

In [55]:
#Function to extract price
def get_price():
    price=[]
    prices=driver.find_elements_by_xpath("//div[@class='above-button']")
    for i in range(0,len(prices),2):
        price.append(prices[i])
    return price

PART-D(end)
PART-D contains the various functions to extract specific information from different pages.

PART-E(start)

In [1]:
#These lists have to be initialised every time we are to use them
price_=[]
airlines_=[]
time_=[]
duration_=[]
stops_=[]
airports_=[]
website_=[]

In [1330]:
#Using the functions defined above to scrape the desired results
airline_el=get_airline()
airlines_.extend(scrape_text(airline_el))
price_el=get_price()
price_.extend(scrape_text(price_el))
time_el=get_times()
time_.extend(scrape_text(time_el))
duration_el=get_duration()
duration_.extend(scrape_text(duration_el))
stops_el=get_stops()
stops_.extend(scrape_text(stops_el))
airport_el=get_airports()
airports_.extend(scrape_text(airport_el))
website_el=get_website()
website_.extend(scrape_text(website_el))
print(len(website_))
print(len(airlines_))
print(len(price_))
print(len(time_))
print(len(duration_))
print(len(stops_))
print(len(airports_))

42
42
42
168
84
84
168

The above code is to determine the lengths of all the features scraped which are added to the lists below only if the lengths are identical i.e price_,duration_,stops_ etc. have equal lengths while time_ and airports_ have double the length of the price_.This is because the same web element for arrival and departure was used.

In [73]:
def remove_null(list1):
    list2=[]
    for i in list1:
        if(i==''):
            continue
        else:
            list2.append(i)
    return list2

In [2]:
#initialising the lists (Only to be initialised once)
#airlines=[]
#price=[]
#time1=[]
#duration=[]
#stops=[]
#airports=[]
#website=[]

In [1331]:
#Adding the above scraped lists if they fulfill the criteria of identical lengths
price.extend(remove_null(price_))
airports.extend(remove_null(airports_))
stops.extend(remove_null(stops_))
duration.extend(remove_null(duration_))
time1.extend(remove_null(time_))
airlines.extend(remove_null(airlines_))
website.extend(remove_null(website_))

In [1332]:
print(len(price))
print(len(airlines))
print(len(airports))
print(len(time1))
print(len(stops))

2556
2556
5112
5112
2556

PART-E(end)
Part-E is there to extract data into different lists respectively and check if the lists are propotionate in lengths i.e except the time1 and airports lists all the other lists have equal lengths while the former have double their lengths as they have informations of the origin and destination for every flight.
The blocks A to E have to be executed repeatedly until sufficient data is scraped.

PART-F(start)

In [1333]:
#making a copy
airlines2=airlines

price2=price
time2=time1
duration2=duration
stops2=stops
airports2=airports
website2=website

In [1334]:
#Separating the arrival and departure airport names and timings
arrival_time=[]
departure_time=[]
arrival_airport=[]
departure_airport=[]
#=[]
#arrival=[]

In [1335]:
#Code for separating the arrival and departure timings and airports
for j in range(0,len(time1)):
    
               
    if(j%2==0):
        
        departure_time.append(time1[j])
        departure_airport.append(airports[j])
    elif(j%2!=0):
        
        
        arrival_time.append(time1[j])
        arrival_airport.append(airports[j])
print(len(arrival_time))
print(len(departure_airport))

2556
2556

In [878]:
import re 

import string
from nltk.tokenize import word_tokenize
from nltk.tokenize import sent_tokenize

In [879]:
#clean the data after finishing scraping

In [1336]:
date1=[]
day1=[]
date2=[]

In [ ]:
#Inserting the date on which the data was recorded,date of journey,day of journey(To be altered accordigly)
for date in range(len(stops)):
    date1.append('13/02/2022')
    day1.append('SUNDAY')
    date2.append("27/01/2022")
len(date1)
len(day1)
len(date2)

Finally creating a dataframe to store all the scraped data

In [1338]:
import pandas as pd
df3=pd.DataFrame()
df3['Date_recorded']=date2
df3['Airline_name']=airlines
df3['Website']=website
df3['Date_of_journey']=date1
df3['Day_of_journey']=day1
df3['Departure_time']=departure_time
df3['Arrival_time']=arrival_time
df3['Origin']=departure_airport
df3['Destination']=arrival_airport
df3['Stops']=stops
df3['Duration']=duration
df3['Price']=price
df3

,Date_recorded,Airline_name,Website,Date_of_journey,Day_of_journey,Departure_time,Arrival_time,Origin,Destination,Stops,Duration,Price
0,27/01/2022,Vistara,15 sites,13/02/2022,SUNDAY,12:25,14:30,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 05m,"₹ 1,945"
1,27/01/2022,Vistara,15 sites,13/02/2022,SUNDAY,06:30,08:35,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 05m,"₹ 1,945"
2,27/01/2022,Vistara,15 sites,13/02/2022,SUNDAY,20:55,23:00,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 05m,"₹ 1,945"
3,27/01/2022,Vistara,15 sites,13/02/2022,SUNDAY,22:45,00:55 +1,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 10m,"₹ 1,945"
4,27/01/2022,Vistara,15 sites,13/02/2022,SUNDAY,18:30,20:40,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 10m,"₹ 1,945"
...,...,...,...,...,...,...,...,...,...,...,...,...
2551,27/01/2022,"IndiGo, GoFirst",Kiwi.com,13/02/2022,SUNDAY,06:10,11:00,BLR Bengaluru Intl,PAT Patna,"1 stop,HYD",4h 50m,"₹ 8,462"
2552,27/01/2022,"Vistara, IndiGo",Gotogate,13/02/2022,SUNDAY,07:55,16:10,BLR Bengaluru Intl,PAT Patna,"1 stop,HYD",8h 15m,"₹ 9,059"
2553,27/01/2022,"Air India, GoFirst",Kiwi.com,13/02/2022,SUNDAY,06:30,11:00,BLR Bengaluru Intl,PAT Patna,"1 stop,HYD",4h 30m,"₹ 9,280"
2554,27/01/2022,"IndiGo, SpiceJet",Kiwi.com,13/02/2022,SUNDAY,02:45,10:05,BLR Bengaluru Intl,PAT Patna,"1 stop,AMD",7h 20m,"₹ 11,866"
2555,27/01/2022,SpiceJet,8 sites,13/02/2022,SUNDAY,15:45,17:55,BLR Bengaluru Intl,PAT Patna,direct,2h 10m,"₹ 17,380"

In [1340]:
#Saving/storing the dataframe in csv format
df3.to_csv("flight_price_prediction(final_dataset2).csv")

PART-F(end)
PART-F is there to filter the required information from the scraped data,creating a DataFrame for it and storing it as a csv file.

PART-G(start)

In [884]:
#searched={"origin_names":origin_names,"destination_names":destination_names}

In [885]:
#creating a dataframe to store the names of the airports searched for future references
#df_searched=pd.DataFrame(data=searched)
#df_searched

In [886]:
#df_searched.drop([13,14],inplace=True)

In [887]:
#df_searched.to_csv("Flight_price(searched)")

CONCATENATING ALL THE SCRAPED DATASETS INTO ONE AND PERFORMING NECESSARY MODIFICATIONS.

In [888]:
df_1=pd.read_csv("flight_price(set-1).csv")
df_1

,Unnamed: 0,Date_recorded,Airline_name,Website,Date_of_journey,Day_of_journey,Departure_time,Arrival_time,Origin,Destination,Stops,Duration,Price
0,0,24/01/2022,Vistara,BudgetTicket,23/02/2022,WEDNESDAY,06:30,08:35,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 05m,"₹ 1,865"
1,1,24/01/2022,Vistara,BudgetTicket,23/02/2022,WEDNESDAY,06:00,08:05,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 05m,"₹ 1,865"
2,2,24/01/2022,Vistara,BudgetTicket,23/02/2022,WEDNESDAY,20:55,23:00,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 05m,"₹ 1,865"
3,3,24/01/2022,Vistara,BudgetTicket,23/02/2022,WEDNESDAY,12:25,14:30,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 05m,"₹ 1,865"
4,4,24/01/2022,Vistara,BudgetTicket,23/02/2022,WEDNESDAY,18:30,20:40,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 10m,"₹ 1,865"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,751,24/01/2022,"British Airways, Air Canada",Air Canada,23/02/2022,WEDNESDAY,20:50,19:29 +1,CPT Cape Town Intl,YYZ Pearson Intl,"2 stops,LHR, YUL",29h 39m,"₹ 192,725"
752,752,24/01/2022,"British Airways, Air Canada",Air Canada,23/02/2022,WEDNESDAY,18:55,19:29 +1,CPT Cape Town Intl,YYZ Pearson Intl,"2 stops,LHR, YUL",31h 34m,"₹ 192,725"
753,753,24/01/2022,"Qatar Airways, Air Canada",Air Canada,23/02/2022,WEDNESDAY,12:55,12:20 +1,CPT Cape Town Intl,YYZ Pearson Intl,"2 stops,DOH, FRA",30h 25m,"₹ 215,596"
754,754,24/01/2022,"British Airways, Air Canada",Air Canada,23/02/2022,WEDNESDAY,17:30,14:00 +1,CPT Cape Town Intl,YYZ Pearson Intl,"2 stops,JNB, LHR",27h 30m,"₹ 240,584"
755,755,24/01/2022,"Emirates, Air Canada",Bravofly,23/02/2022,WEDNESDAY,18:25,19:43 +1,CPT Cape Town Intl,YYZ Pearson Intl,"2 stops,DXB, BOS",32h 18m,"₹ 660,190"

In [889]:
df_2=pd.read_csv("flight_price(set-2).csv")
df_2

,Unnamed: 0,Date_recorded,Airline_name,Website,Date_of_journey,Day_of_journey,Departure_time,Arrival_time,Origin,Destination,Stops,Duration,Price
0,0,25/01/2022,"Spirit Airlines, Air Canada",Kiwi.com,23/02/2022,WEDNESDAY,14:20,00:01 +1,ORD O'Hare Intl,YYZ Pearson Intl,"1 stop,MIA",8h 41m,"₹ 6,865"
1,1,25/01/2022,Porter Airlines,Bravofly,23/02/2022,WEDNESDAY,16:20,18:57,MDW Midway,YTZ Toronto Island,direct,1h 37m,"₹ 7,091"
2,2,25/01/2022,Air Canada,iWofly,23/02/2022,WEDNESDAY,06:30,09:05,ORD O'Hare Intl,YYZ Pearson Intl,direct,1h 35m,"₹ 7,363"
3,3,25/01/2022,Air Canada,iWofly,23/02/2022,WEDNESDAY,09:50,12:25,ORD O'Hare Intl,YYZ Pearson Intl,direct,1h 35m,"₹ 7,363"
4,4,25/01/2022,Air Canada,iWofly,23/02/2022,WEDNESDAY,13:55,16:30,ORD O'Hare Intl,YYZ Pearson Intl,direct,1h 35m,"₹ 7,363"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1791,1791,25/01/2022,"Vistara, IndiGo",Gotogate,23/02/2022,WEDNESDAY,06:40,16:10,BLR Bengaluru Intl,PAT Patna,"2 stops,BOM, HYD",9h 30m,"₹ 7,107"
1792,1792,25/01/2022,Air India,mytrip.com,23/02/2022,WEDNESDAY,02:40,12:10,BLR Bengaluru Intl,PAT Patna,"2 stops,CCU, DEL",9h 30m,"₹ 7,604"
1793,1793,25/01/2022,"IndiGo, GoFirst",Kiwi.com,23/02/2022,WEDNESDAY,06:10,11:00,BLR Bengaluru Intl,PAT Patna,"1 stop,HYD",4h 50m,"₹ 8,461"
1794,1794,25/01/2022,"IndiGo, SpiceJet",Kiwi.com,23/02/2022,WEDNESDAY,02:45,10:05,BLR Bengaluru Intl,PAT Patna,"1 stop,AMD",7h 20m,"₹ 11,907"
1795,1795,25/01/2022,Vistara,happyfares,23/02/2022,WEDNESDAY,11:30,19:55,BLR Bengaluru Intl,PAT Patna,"2 stops,IXC, DEL",8h 25m,"₹ 12,463"

In [890]:
df_3=pd.read_csv("flight_price(set-3).csv")
df_3

,Unnamed: 0,Date_recorded,Airline_name,Website,Date_of_journey,Day_of_journey,Departure_time,Arrival_time,Origin,Destination,Stops,Duration,Price
0,0,25/01/2022,SpiceJet,Travomint,28/01/2022,Friday,21:45,23:55,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 10m,"₹ 5,242"
1,1,25/01/2022,SpiceJet,Travomint,28/01/2022,Friday,07:20,09:35,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 15m,"₹ 5,242"
2,2,25/01/2022,GoFirst,Travomint,28/01/2022,Friday,20:15,22:25,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 10m,"₹ 5,380"
3,3,25/01/2022,GoFirst,Travomint,28/01/2022,Friday,06:00,08:10,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 10m,"₹ 5,380"
4,4,25/01/2022,GoFirst,Travomint,28/01/2022,Friday,08:20,10:30,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 10m,"₹ 5,380"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2054,2054,25/01/2022,IndiGo,Gotogate,28/01/2022,Friday,08:05,17:45,BLR Bengaluru Intl,PAT Patna,"2 stops,BOM, DEL",9h 40m,"₹ 14,739"
2055,2055,25/01/2022,Air India,Tripmonster,28/01/2022,Friday,02:40,12:10,BLR Bengaluru Intl,PAT Patna,"2 stops,CCU, DEL",9h 30m,"₹ 14,969"
2056,2056,25/01/2022,"Vistara, IndiGo",Gotogate,28/01/2022,Friday,07:00,13:50,BLR Bengaluru Intl,PAT Patna,"1 stop,DEL",6h 50m,"₹ 15,157"
2057,2057,25/01/2022,"Vistara, IndiGo",Gotogate,28/01/2022,Friday,09:45,17:45,BLR Bengaluru Intl,PAT Patna,"1 stop,DEL",8h 00m,"₹ 15,435"
2058,2058,25/01/2022,IndiGo,Gotogate,28/01/2022,Friday,10:05,19:15,BLR Bengaluru Intl,PAT Patna,"2 stops,NAG, DEL",9h 10m,"₹ 16,900"

In [891]:
df=pd.concat([df_1,df_2,df_3])
df

,Unnamed: 0,Date_recorded,Airline_name,Website,Date_of_journey,Day_of_journey,Departure_time,Arrival_time,Origin,Destination,Stops,Duration,Price
0,0,24/01/2022,Vistara,BudgetTicket,23/02/2022,WEDNESDAY,06:30,08:35,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 05m,"₹ 1,865"
1,1,24/01/2022,Vistara,BudgetTicket,23/02/2022,WEDNESDAY,06:00,08:05,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 05m,"₹ 1,865"
2,2,24/01/2022,Vistara,BudgetTicket,23/02/2022,WEDNESDAY,20:55,23:00,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 05m,"₹ 1,865"
3,3,24/01/2022,Vistara,BudgetTicket,23/02/2022,WEDNESDAY,12:25,14:30,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 05m,"₹ 1,865"
4,4,24/01/2022,Vistara,BudgetTicket,23/02/2022,WEDNESDAY,18:30,20:40,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 10m,"₹ 1,865"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2054,2054,25/01/2022,IndiGo,Gotogate,28/01/2022,Friday,08:05,17:45,BLR Bengaluru Intl,PAT Patna,"2 stops,BOM, DEL",9h 40m,"₹ 14,739"
2055,2055,25/01/2022,Air India,Tripmonster,28/01/2022,Friday,02:40,12:10,BLR Bengaluru Intl,PAT Patna,"2 stops,CCU, DEL",9h 30m,"₹ 14,969"
2056,2056,25/01/2022,"Vistara, IndiGo",Gotogate,28/01/2022,Friday,07:00,13:50,BLR Bengaluru Intl,PAT Patna,"1 stop,DEL",6h 50m,"₹ 15,157"
2057,2057,25/01/2022,"Vistara, IndiGo",Gotogate,28/01/2022,Friday,09:45,17:45,BLR Bengaluru Intl,PAT Patna,"1 stop,DEL",8h 00m,"₹ 15,435"
2058,2058,25/01/2022,IndiGo,Gotogate,28/01/2022,Friday,10:05,19:15,BLR Bengaluru Intl,PAT Patna,"2 stops,NAG, DEL",9h 10m,"₹ 16,900"

In [892]:
df.isnull().sum()

Unnamed: 0         0
Date_recorded      0
Airline_name       0
Website            0
Date_of_journey    0
Day_of_journey     0
Departure_time     0
Arrival_time       0
Origin             0
Destination        0
Stops              0
Duration           0
Price              0
dtype: int64

In [894]:
df.to_csv("flight_price_prediction(final_dataset).csv")

In [1]:
import pandas as pd
df1=pd.read_csv("flight_price_prediction(final_dataset).csv")
df1

,Unnamed: 0,Unnamed: 0.1,Date_recorded,Airline_name,Website,Date_of_journey,Day_of_journey,Departure_time,Arrival_time,Origin,Destination,Stops,Duration,Price
0,0,0,24/01/2022,Vistara,BudgetTicket,23/02/2022,WEDNESDAY,06:30,08:35,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 05m,"₹ 1,865"
1,1,1,24/01/2022,Vistara,BudgetTicket,23/02/2022,WEDNESDAY,06:00,08:05,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 05m,"₹ 1,865"
2,2,2,24/01/2022,Vistara,BudgetTicket,23/02/2022,WEDNESDAY,20:55,23:00,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 05m,"₹ 1,865"
3,3,3,24/01/2022,Vistara,BudgetTicket,23/02/2022,WEDNESDAY,12:25,14:30,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 05m,"₹ 1,865"
4,4,4,24/01/2022,Vistara,BudgetTicket,23/02/2022,WEDNESDAY,18:30,20:40,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 10m,"₹ 1,865"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4606,2054,2054,25/01/2022,IndiGo,Gotogate,28/01/2022,Friday,08:05,17:45,BLR Bengaluru Intl,PAT Patna,"2 stops,BOM, DEL",9h 40m,"₹ 14,739"
4607,2055,2055,25/01/2022,Air India,Tripmonster,28/01/2022,Friday,02:40,12:10,BLR Bengaluru Intl,PAT Patna,"2 stops,CCU, DEL",9h 30m,"₹ 14,969"
4608,2056,2056,25/01/2022,"Vistara, IndiGo",Gotogate,28/01/2022,Friday,07:00,13:50,BLR Bengaluru Intl,PAT Patna,"1 stop,DEL",6h 50m,"₹ 15,157"
4609,2057,2057,25/01/2022,"Vistara, IndiGo",Gotogate,28/01/2022,Friday,09:45,17:45,BLR Bengaluru Intl,PAT Patna,"1 stop,DEL",8h 00m,"₹ 15,435"
4610,2058,2058,25/01/2022,IndiGo,Gotogate,28/01/2022,Friday,10:05,19:15,BLR Bengaluru Intl,PAT Patna,"2 stops,NAG, DEL",9h 10m,"₹ 16,900"

In [2]:
df2=pd.read_csv("flight_price_prediction(final_dataset2).csv")
df2

,Unnamed: 0,Date_recorded,Airline_name,Website,Date_of_journey,Day_of_journey,Departure_time,Arrival_time,Origin,Destination,Stops,Duration,Price
0,0,27/01/2022,Vistara,15 sites,13/02/2022,SUNDAY,12:25,14:30,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 05m,"₹ 1,945"
1,1,27/01/2022,Vistara,15 sites,13/02/2022,SUNDAY,06:30,08:35,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 05m,"₹ 1,945"
2,2,27/01/2022,Vistara,15 sites,13/02/2022,SUNDAY,20:55,23:00,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 05m,"₹ 1,945"
3,3,27/01/2022,Vistara,15 sites,13/02/2022,SUNDAY,22:45,00:55 +1,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 10m,"₹ 1,945"
4,4,27/01/2022,Vistara,15 sites,13/02/2022,SUNDAY,18:30,20:40,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 10m,"₹ 1,945"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2551,2551,27/01/2022,"IndiGo, GoFirst",Kiwi.com,13/02/2022,SUNDAY,06:10,11:00,BLR Bengaluru Intl,PAT Patna,"1 stop,HYD",4h 50m,"₹ 8,462"
2552,2552,27/01/2022,"Vistara, IndiGo",Gotogate,13/02/2022,SUNDAY,07:55,16:10,BLR Bengaluru Intl,PAT Patna,"1 stop,HYD",8h 15m,"₹ 9,059"
2553,2553,27/01/2022,"Air India, GoFirst",Kiwi.com,13/02/2022,SUNDAY,06:30,11:00,BLR Bengaluru Intl,PAT Patna,"1 stop,HYD",4h 30m,"₹ 9,280"
2554,2554,27/01/2022,"IndiGo, SpiceJet",Kiwi.com,13/02/2022,SUNDAY,02:45,10:05,BLR Bengaluru Intl,PAT Patna,"1 stop,AMD",7h 20m,"₹ 11,866"
2555,2555,27/01/2022,SpiceJet,8 sites,13/02/2022,SUNDAY,15:45,17:55,BLR Bengaluru Intl,PAT Patna,direct,2h 10m,"₹ 17,380"

In [3]:
df1.drop("Unnamed: 0.1",axis=1,inplace=True)

In [4]:
df=pd.concat([df1,df2])
df

,Unnamed: 0,Date_recorded,Airline_name,Website,Date_of_journey,Day_of_journey,Departure_time,Arrival_time,Origin,Destination,Stops,Duration,Price
0,0,24/01/2022,Vistara,BudgetTicket,23/02/2022,WEDNESDAY,06:30,08:35,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 05m,"₹ 1,865"
1,1,24/01/2022,Vistara,BudgetTicket,23/02/2022,WEDNESDAY,06:00,08:05,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 05m,"₹ 1,865"
2,2,24/01/2022,Vistara,BudgetTicket,23/02/2022,WEDNESDAY,20:55,23:00,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 05m,"₹ 1,865"
3,3,24/01/2022,Vistara,BudgetTicket,23/02/2022,WEDNESDAY,12:25,14:30,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 05m,"₹ 1,865"
4,4,24/01/2022,Vistara,BudgetTicket,23/02/2022,WEDNESDAY,18:30,20:40,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 10m,"₹ 1,865"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2551,2551,27/01/2022,"IndiGo, GoFirst",Kiwi.com,13/02/2022,SUNDAY,06:10,11:00,BLR Bengaluru Intl,PAT Patna,"1 stop,HYD",4h 50m,"₹ 8,462"
2552,2552,27/01/2022,"Vistara, IndiGo",Gotogate,13/02/2022,SUNDAY,07:55,16:10,BLR Bengaluru Intl,PAT Patna,"1 stop,HYD",8h 15m,"₹ 9,059"
2553,2553,27/01/2022,"Air India, GoFirst",Kiwi.com,13/02/2022,SUNDAY,06:30,11:00,BLR Bengaluru Intl,PAT Patna,"1 stop,HYD",4h 30m,"₹ 9,280"
2554,2554,27/01/2022,"IndiGo, SpiceJet",Kiwi.com,13/02/2022,SUNDAY,02:45,10:05,BLR Bengaluru Intl,PAT Patna,"1 stop,AMD",7h 20m,"₹ 11,866"
2555,2555,27/01/2022,SpiceJet,8 sites,13/02/2022,SUNDAY,15:45,17:55,BLR Bengaluru Intl,PAT Patna,direct,2h 10m,"₹ 17,380"

In [5]:
df=pd.read_csv('flight_price_prediction(final_dataset_new).csv')
df

,Unnamed: 0,Unnamed: 0.1,Date_recorded,Airline_name,Website,Date_of_journey,Day_of_journey,Departure_time,Arrival_time,Origin,Destination,Stops,Duration,Price
0,0,0,24/01/2022,Vistara,BudgetTicket,23/02/2022,WEDNESDAY,06:30,08:35,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 05m,"₹ 1,865"
1,1,1,24/01/2022,Vistara,BudgetTicket,23/02/2022,WEDNESDAY,06:00,08:05,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 05m,"₹ 1,865"
2,2,2,24/01/2022,Vistara,BudgetTicket,23/02/2022,WEDNESDAY,20:55,23:00,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 05m,"₹ 1,865"
3,3,3,24/01/2022,Vistara,BudgetTicket,23/02/2022,WEDNESDAY,12:25,14:30,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 05m,"₹ 1,865"
4,4,4,24/01/2022,Vistara,BudgetTicket,23/02/2022,WEDNESDAY,18:30,20:40,BOM Chhatrapati Shivaji Intl,DEL Indira Gandhi Intl,direct,2h 10m,"₹ 1,865"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7162,2551,2551,27/01/2022,"IndiGo, GoFirst",Kiwi.com,13/02/2022,SUNDAY,06:10,11:00,BLR Bengaluru Intl,PAT Patna,"1 stop,HYD",4h 50m,"₹ 8,462"
7163,2552,2552,27/01/2022,"Vistara, IndiGo",Gotogate,13/02/2022,SUNDAY,07:55,16:10,BLR Bengaluru Intl,PAT Patna,"1 stop,HYD",8h 15m,"₹ 9,059"
7164,2553,2553,27/01/2022,"Air India, GoFirst",Kiwi.com,13/02/2022,SUNDAY,06:30,11:00,BLR Bengaluru Intl,PAT Patna,"1 stop,HYD",4h 30m,"₹ 9,280"
7165,2554,2554,27/01/2022,"IndiGo, SpiceJet",Kiwi.com,13/02/2022,SUNDAY,02:45,10:05,BLR Bengaluru Intl,PAT Patna,"1 stop,AMD",7h 20m,"₹ 11,866"
7166,2555,2555,27/01/2022,SpiceJet,8 sites,13/02/2022,SUNDAY,15:45,17:55,BLR Bengaluru Intl,PAT Patna,direct,2h 10m,"₹ 17,380"

In [6]:
df.to_excel('flight_price_prediction(final_dataset_new).xlsx')

In [6]:
#df.to_csv("flight_price_prediction(final_dataset_new).csv")

PART-G(end)
PART-G need not be executed.
It is there because data was scraped over a period of 3-4 days and stored as a different csv file.Hence,all the datasets had to be combined before using them in our worksheet.

END OF WEB-SCRAPING